#!/bin/bash

echo "🔧 設定 Queue Worker 的 SERVICE_API_TOKEN"
echo ""
echo "請注意:這個 token 必須與 Server 的 SERVICE_API_TOKEN 相同"
echo ""
echo "執行以下命令來設定:"
echo ""
echo "cd apps/queue-worker"
echo "wrangler secret put SERVICE_API_TOKEN"
echo ""
echo "然後輸入與 Server 相同的 token 值"
echo ""
echo "如果您不知道 Server 的 token 值,可以:"
echo "1. 在 Cloudflare Dashboard 查看"
echo "2. 或者重新生成一個新的 token 並同時更新 Server 和 Queue Worker"
echo ""
echo "生成新 token 的建議命令:"
echo "openssl rand -base64 32"
