/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TodosIndexRouteImport } from './routes/todos/index'
import { Route as ReportsIndexRouteImport } from './routes/reports/index'
import { Route as OpportunitiesIndexRouteImport } from './routes/opportunities/index'
import { Route as ConversationsIndexRouteImport } from './routes/conversations/index'
import { Route as AlertsIndexRouteImport } from './routes/alerts/index'
import { Route as TodosTeamRouteImport } from './routes/todos/team'
import { Route as ShareTokenRouteImport } from './routes/share/$token'
import { Route as ReportsMtdUploadsRouteImport } from './routes/reports/mtd-uploads'
import { Route as OpportunitiesNewRouteImport } from './routes/opportunities/new'
import { Route as OpportunitiesIdRouteImport } from './routes/opportunities/$id'
import { Route as ConversationsNewRouteImport } from './routes/conversations/new'
import { Route as ConversationsIdRouteImport } from './routes/conversations/$id'
import { Route as AlertsAlertIdRouteImport } from './routes/alerts/$alertId'
import { Route as AdminTeamRouteImport } from './routes/admin/team'
import { Route as OpportunitiesIdEditRouteImport } from './routes/opportunities/$id/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosIndexRoute = TodosIndexRouteImport.update({
  id: '/todos/',
  path: '/todos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIndexRoute = OpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsIndexRoute = ConversationsIndexRouteImport.update({
  id: '/conversations/',
  path: '/conversations/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsIndexRoute = AlertsIndexRouteImport.update({
  id: '/alerts/',
  path: '/alerts/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosTeamRoute = TodosTeamRouteImport.update({
  id: '/todos/team',
  path: '/todos/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsMtdUploadsRoute = ReportsMtdUploadsRouteImport.update({
  id: '/reports/mtd-uploads',
  path: '/reports/mtd-uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesNewRoute = OpportunitiesNewRouteImport.update({
  id: '/opportunities/new',
  path: '/opportunities/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIdRoute = OpportunitiesIdRouteImport.update({
  id: '/opportunities/$id',
  path: '/opportunities/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsNewRoute = ConversationsNewRouteImport.update({
  id: '/conversations/new',
  path: '/conversations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsIdRoute = ConversationsIdRouteImport.update({
  id: '/conversations/$id',
  path: '/conversations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsAlertIdRoute = AlertsAlertIdRouteImport.update({
  id: '/alerts/$alertId',
  path: '/alerts/$alertId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/admin/team',
  path: '/admin/team',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIdEditRoute = OpportunitiesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => OpportunitiesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/admin/team': typeof AdminTeamRoute
  '/alerts/$alertId': typeof AlertsAlertIdRoute
  '/conversations/$id': typeof ConversationsIdRoute
  '/conversations/new': typeof ConversationsNewRoute
  '/opportunities/$id': typeof OpportunitiesIdRouteWithChildren
  '/opportunities/new': typeof OpportunitiesNewRoute
  '/reports/mtd-uploads': typeof ReportsMtdUploadsRoute
  '/share/$token': typeof ShareTokenRoute
  '/todos/team': typeof TodosTeamRoute
  '/alerts': typeof AlertsIndexRoute
  '/conversations': typeof ConversationsIndexRoute
  '/opportunities': typeof OpportunitiesIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/todos': typeof TodosIndexRoute
  '/opportunities/$id/edit': typeof OpportunitiesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/admin/team': typeof AdminTeamRoute
  '/alerts/$alertId': typeof AlertsAlertIdRoute
  '/conversations/$id': typeof ConversationsIdRoute
  '/conversations/new': typeof ConversationsNewRoute
  '/opportunities/$id': typeof OpportunitiesIdRouteWithChildren
  '/opportunities/new': typeof OpportunitiesNewRoute
  '/reports/mtd-uploads': typeof ReportsMtdUploadsRoute
  '/share/$token': typeof ShareTokenRoute
  '/todos/team': typeof TodosTeamRoute
  '/alerts': typeof AlertsIndexRoute
  '/conversations': typeof ConversationsIndexRoute
  '/opportunities': typeof OpportunitiesIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/todos': typeof TodosIndexRoute
  '/opportunities/$id/edit': typeof OpportunitiesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/admin/team': typeof AdminTeamRoute
  '/alerts/$alertId': typeof AlertsAlertIdRoute
  '/conversations/$id': typeof ConversationsIdRoute
  '/conversations/new': typeof ConversationsNewRoute
  '/opportunities/$id': typeof OpportunitiesIdRouteWithChildren
  '/opportunities/new': typeof OpportunitiesNewRoute
  '/reports/mtd-uploads': typeof ReportsMtdUploadsRoute
  '/share/$token': typeof ShareTokenRoute
  '/todos/team': typeof TodosTeamRoute
  '/alerts/': typeof AlertsIndexRoute
  '/conversations/': typeof ConversationsIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/todos/': typeof TodosIndexRoute
  '/opportunities/$id/edit': typeof OpportunitiesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/admin/team'
    | '/alerts/$alertId'
    | '/conversations/$id'
    | '/conversations/new'
    | '/opportunities/$id'
    | '/opportunities/new'
    | '/reports/mtd-uploads'
    | '/share/$token'
    | '/todos/team'
    | '/alerts'
    | '/conversations'
    | '/opportunities'
    | '/reports'
    | '/todos'
    | '/opportunities/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/admin/team'
    | '/alerts/$alertId'
    | '/conversations/$id'
    | '/conversations/new'
    | '/opportunities/$id'
    | '/opportunities/new'
    | '/reports/mtd-uploads'
    | '/share/$token'
    | '/todos/team'
    | '/alerts'
    | '/conversations'
    | '/opportunities'
    | '/reports'
    | '/todos'
    | '/opportunities/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/admin/team'
    | '/alerts/$alertId'
    | '/conversations/$id'
    | '/conversations/new'
    | '/opportunities/$id'
    | '/opportunities/new'
    | '/reports/mtd-uploads'
    | '/share/$token'
    | '/todos/team'
    | '/alerts/'
    | '/conversations/'
    | '/opportunities/'
    | '/reports/'
    | '/todos/'
    | '/opportunities/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AlertsAlertIdRoute: typeof AlertsAlertIdRoute
  ConversationsIdRoute: typeof ConversationsIdRoute
  ConversationsNewRoute: typeof ConversationsNewRoute
  OpportunitiesIdRoute: typeof OpportunitiesIdRouteWithChildren
  OpportunitiesNewRoute: typeof OpportunitiesNewRoute
  ReportsMtdUploadsRoute: typeof ReportsMtdUploadsRoute
  ShareTokenRoute: typeof ShareTokenRoute
  TodosTeamRoute: typeof TodosTeamRoute
  AlertsIndexRoute: typeof AlertsIndexRoute
  ConversationsIndexRoute: typeof ConversationsIndexRoute
  OpportunitiesIndexRoute: typeof OpportunitiesIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  TodosIndexRoute: typeof TodosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos/': {
      id: '/todos/'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/': {
      id: '/opportunities/'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations/': {
      id: '/conversations/'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof ConversationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/': {
      id: '/alerts/'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos/team': {
      id: '/todos/team'
      path: '/todos/team'
      fullPath: '/todos/team'
      preLoaderRoute: typeof TodosTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/mtd-uploads': {
      id: '/reports/mtd-uploads'
      path: '/reports/mtd-uploads'
      fullPath: '/reports/mtd-uploads'
      preLoaderRoute: typeof ReportsMtdUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/new': {
      id: '/opportunities/new'
      path: '/opportunities/new'
      fullPath: '/opportunities/new'
      preLoaderRoute: typeof OpportunitiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/$id': {
      id: '/opportunities/$id'
      path: '/opportunities/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof OpportunitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations/new': {
      id: '/conversations/new'
      path: '/conversations/new'
      fullPath: '/conversations/new'
      preLoaderRoute: typeof ConversationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations/$id': {
      id: '/conversations/$id'
      path: '/conversations/$id'
      fullPath: '/conversations/$id'
      preLoaderRoute: typeof ConversationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/$alertId': {
      id: '/alerts/$alertId'
      path: '/alerts/$alertId'
      fullPath: '/alerts/$alertId'
      preLoaderRoute: typeof AlertsAlertIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/admin/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/$id/edit': {
      id: '/opportunities/$id/edit'
      path: '/edit'
      fullPath: '/opportunities/$id/edit'
      preLoaderRoute: typeof OpportunitiesIdEditRouteImport
      parentRoute: typeof OpportunitiesIdRoute
    }
  }
}

interface OpportunitiesIdRouteChildren {
  OpportunitiesIdEditRoute: typeof OpportunitiesIdEditRoute
}

const OpportunitiesIdRouteChildren: OpportunitiesIdRouteChildren = {
  OpportunitiesIdEditRoute: OpportunitiesIdEditRoute,
}

const OpportunitiesIdRouteWithChildren = OpportunitiesIdRoute._addFileChildren(
  OpportunitiesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  AdminTeamRoute: AdminTeamRoute,
  AlertsAlertIdRoute: AlertsAlertIdRoute,
  ConversationsIdRoute: ConversationsIdRoute,
  ConversationsNewRoute: ConversationsNewRoute,
  OpportunitiesIdRoute: OpportunitiesIdRouteWithChildren,
  OpportunitiesNewRoute: OpportunitiesNewRoute,
  ReportsMtdUploadsRoute: ReportsMtdUploadsRoute,
  ShareTokenRoute: ShareTokenRoute,
  TodosTeamRoute: TodosTeamRoute,
  AlertsIndexRoute: AlertsIndexRoute,
  ConversationsIndexRoute: ConversationsIndexRoute,
  OpportunitiesIndexRoute: OpportunitiesIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  TodosIndexRoute: TodosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
